CREATE TABLE IF NOT EXISTS bets (
  id VARCHAR(64) PRIMARY KEY, event_id VARCHAR(128), league VARCHAR(128),
  market VARCHAR(64), selection VARCHAR(128), odds DOUBLE PRECISION,
  probability DOUBLE PRECISION, fair_odds DOUBLE PRECISION, edge DOUBLE PRECISION,
  ev DOUBLE PRECISION, stake DOUBLE PRECISION, status VARCHAR(16),
  pnl DOUBLE PRECISION DEFAULT 0, closing_odds DOUBLE PRECISION, clv DOUBLE PRECISION,
  created_at TIMESTAMP, live BOOLEAN DEFAULT FALSE, reason TEXT
);
CREATE TABLE IF NOT EXISTS decisions (
  id BIGSERIAL PRIMARY KEY, event_id VARCHAR(128), decision VARCHAR(16),
  reason TEXT, score DOUBLE PRECISION, created_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS model_registry (
  model_id VARCHAR(128) PRIMARY KEY, status VARCHAR(32), metadata JSONB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
